---
- name: Test ping-ping
  hosts: all
  become: yes
  gather_facts: true
  tasks:
  - name: Ping my servers
    ping: 
  - name: print
    ansible.builtin.debug:
      msg: this is the value {{ syslog_remote_host }}
