---
- name: Test ping-ping
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: Ping my servers
    ping: 
  - name: print
    ansible.builtin.debug:
      msg: this is the value {{ hostvars['awxsetup.omid.expertcity.com'] }}
  - name: print booter
    ansible.builtin.debug:
      var: booter
  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts
