---
- name: Test ping-ping
  hosts: awx
  become: yes
  gather_facts: yes
  vars:
    booter: "demo value from playbook"
    nameservers: "2.2.2.2"
  tasks:
  - name: Ping my servers
    ping: 
  - name: print
    ansible.builtin.debug:
      msg: this is the value {{ hostvars[inventory_hostname].nameservers}}
  - name: Print all available facts
    ansible.builtin.debug:
      var: nameservers
