---
- name: Test ping-ping
  hosts: awx
  become: yes
  gather_facts: yes
  vars:
    booter: "demo value from playbook"
  tasks:
  - name: Ping my servers
    ping: 
  - name: print
    ansible.builtin.debug:
      msg: this is the value {{ hostvars.ansible_ssh_host }}
  - name: Print all available facts
    ansible.builtin.debug:
      var: booter
