---
- name: Test ping-ping
  hosts: awx
  become: yes
  gather_facts: yes
  vars:
    booter: "demo value from playbook"
    nameserver: "1.1.1.1"
  tasks:
  - name: Ping my servers
    ping: 
  - name: print
    ansible.builtin.debug:
      msg: this is the value {{ hostvars[inventory_hostname]}}
  - name: Print all available facts
    ansible.builtin.debug:
      var: booter
